import type { Metadata } from "next";
import { Epilogue, Inter, Manrope } from "next/font/google";
import "./globals.css";
import {NextFont} from "next/dist/compiled/@next/font";
import { ToastContainer } from "react-toastify";

import 'react-toastify/dist/ReactToastify.css';

export const inter:NextFont = Inter({ subsets: ["latin"] });

export const epilogue = Epilogue({
  weight: ["400", "300"],
  subsets:["latin"]
})

export const manrope = Manrope({
  weight: ["400", "300"],
  subsets:["latin"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <ToastContainer
          position="bottom-left"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />
      </body>
    </html>
  );
}
