import type { Metadata } from "next";
import { Epilogue, Inter, Manrope } from "next/font/google";
import "./globals.css";

export const inter = Inter({ subsets: ["latin"] });

export const epilogue = Epilogue({
  weight: ["400", "300"],
  subsets:["latin"]
})

export const manrope = Manrope({
  weight: ["400", "300"],
  subsets:["latin"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
