-- AlterTable
ALTER TABLE `Movie` ADD COLUMN `addingTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Series` ADD COLUMN `addingTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `User` MODIFY `password` VARCHAR(191) NULL;
